services:
  php:
    container_name: titania-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    # tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - titania_network
  
  nginx:
    container_name: titania-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    # tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - titania_network
  
  postgres:
    container_name: titania-postgres
    image: postgres:17.4-alpine
    restart: always
    volumes:
      - titania_psql_data:/var/lib/postgresql/data:rw
    networks:
      - titania_network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

networks:
  titania_network:
    driver: bridge

volumes:
  titania_psql_data:
